#!/usr/bin/env python3
"""Build stable monitor outputs and README version sections."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


README_FIELDS = [
    "app_branch",
    "tag_repo",
    "repo_dockerhub",
    "version",
    "base_image",
    "arch_branch",
    "platform_used",
    "status",
]

TARGET_FIELDS = [
    "app_branch",
    "tag_repo",
    "custom_env",
    "runner_image",
    "force_push",
]

START_JSON = "<!-- app-version-json:start -->"
END_JSON = "<!-- app-version-json:end -->"
START_TABLE = "<!-- app-version-table:start -->"
END_TABLE = "<!-- app-version-table:end -->"


def load_json_text(raw: str, fallback: Any) -> Any:
    raw = raw.strip()
    if not raw:
        return fallback
    return json.loads(raw)


def dump_json(data: Any, *, compact: bool = False) -> str:
    if compact:
        return json.dumps(data, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return json.dumps(data, ensure_ascii=False, sort_keys=True, indent=2) + "\n"


def normalize_record(item: dict[str, Any]) -> dict[str, str]:
    return {key: str(item.get(key, "")) for key in README_FIELDS}


def normalize_target(item: dict[str, Any]) -> dict[str, str]:
    target = {key: str(item.get(key, "")) for key in TARGET_FIELDS}
    target["tag_repo"] = target["tag_repo"] or "latest"
    target["runner_image"] = target["runner_image"] or "ubuntu-latest"
    target["force_push"] = target["force_push"] or "false"
    return target


def record_sort_key(item: dict[str, str]) -> tuple[str, str, str]:
    return (item.get("app_branch", ""), item.get("tag_repo", ""), item.get("repo_dockerhub", ""))


def load_version_artifacts(artifact_root: Path) -> list[dict[str, str]]:
    records = []
    for path in sorted(artifact_root.glob("version-*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        records.append(normalize_record(data))
    return sorted(records, key=record_sort_key)


def parse_readme_versions(text: str) -> list[dict[str, str]]:
    if START_JSON not in text or END_JSON not in text:
        return []
    if text.index(START_JSON) >= text.index(END_JSON):
        return []

    segment = text.split(START_JSON, 1)[1].split(END_JSON, 1)[0].strip()
    if segment.startswith("```json"):
        segment = segment[len("```json") :].strip()
    if segment.endswith("```"):
        segment = segment[:-3].strip()
    if not segment:
        return []

    data = json.loads(segment)
    if not isinstance(data, list):
        return []
    return sorted((normalize_record(item) for item in data if isinstance(item, dict)), key=record_sort_key)


def replace_or_append(text: str, start: str, end: str, content: str) -> str:
    block = f"{start}\n{content}\n{end}"
    if start in text and end in text and text.index(start) < text.index(end):
        before = text.split(start, 1)[0]
        after = text.split(end, 1)[1]
        return before + block + after

    prefix = text if text.endswith("\n") else text + "\n"
    return prefix + "\n" + block + "\n"


def markdown_cell(value: str) -> str:
    return value.replace("\n", " ").replace("|", "\\|")


def render_table(records: list[dict[str, str]], workflow_name: str) -> str:
    header = [
        f"Auto-generated by {workflow_name}",
        "Volatile run metadata is intentionally omitted; this section changes only when semantic image state changes.",
        "",
        "| app_branch | tag_repo | repo_dockerhub | version | base_image | arch_branch | platform_used | status |",
        "|---|---|---|---|---|---|---|---|",
    ]
    rows = []
    for item in records:
        rows.append(
            "| "
            + " | ".join(markdown_cell(item[field]) for field in README_FIELDS)
            + " |"
        )
    return "\n".join(header + rows)


def render_readme(text: str, records: list[dict[str, str]], workflow_name: str) -> str:
    new_text = text
    if "## Container Version Matrix" not in new_text:
        if not new_text.endswith("\n"):
            new_text += "\n"
        new_text += "\n## Container Version Matrix\n\nThis section is maintained automatically by GitHub Actions.\n"

    table_block = render_table(records, workflow_name)
    json_block = "```json\n" + dump_json(records).rstrip("\n") + "\n```"
    new_text = replace_or_append(new_text, START_TABLE, END_TABLE, table_block)
    new_text = replace_or_append(new_text, START_JSON, END_JSON, json_block)
    return new_text


def semantic_changed_apps(old_records: list[dict[str, str]], new_records: list[dict[str, str]]) -> list[str]:
    old_map = {
        (item["app_branch"], item["tag_repo"], item["repo_dockerhub"]): item
        for item in old_records
    }
    changed = []
    seen = set()
    for item in new_records:
        key = (item["app_branch"], item["tag_repo"], item["repo_dockerhub"])
        app = item["app_branch"]
        if old_map.get(key) != item and app not in seen:
            seen.add(app)
            changed.append(app)
    return sorted(changed)


def select_build_targets(build_targets: dict[str, Any], changed_apps: list[str], force_build: bool) -> list[dict[str, str]]:
    targets = build_targets.get("include", [])
    if not isinstance(targets, list):
        targets = []

    selected_apps = {target.get("app_branch", "") for target in targets} if force_build else set(changed_apps)
    selected = []
    for target in targets:
        if not isinstance(target, dict):
            continue
        if str(target.get("app_branch", "")) in selected_apps:
            selected.append(normalize_target(target))
    return selected


def render_report(state: dict[str, Any], build_matrix: dict[str, Any]) -> str:
    lines = [
        "# Monitor Report",
        "",
        "This artifact is generated from semantic monitor state. Volatile run metadata is omitted.",
        "",
        f"- Force build: {str(state['force_build']).lower()}",
        f"- README changed: {str(state['readme_changed']).lower()}",
        f"- Changed apps: {len(state['changed_apps'])}",
        f"- Build targets: {state['changed_count']}",
        "",
        "## Changed Apps",
        "",
    ]
    if state["changed_apps"]:
        lines.extend(f"- `{app}`" for app in state["changed_apps"])
    else:
        lines.append("- None")

    lines.extend(
        [
            "",
            "## Build Matrix",
            "",
            "```json",
            dump_json(build_matrix).rstrip("\n"),
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def write_outputs(output_dir: Path, state: dict[str, Any], build_matrix: dict[str, Any], report: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "monitor-state.json").write_text(dump_json(state), encoding="utf-8")
    (output_dir / "build-matrix.json").write_text(dump_json(build_matrix), encoding="utf-8")
    (output_dir / "monitor-report.md").write_text(report, encoding="utf-8")
    (output_dir / "versions.json").write_text(dump_json(state["versions"]), encoding="utf-8")
    (output_dir / "changed-apps.json").write_text(dump_json(state["changed_apps"]), encoding="utf-8")
    (output_dir / "readme_changed.txt").write_text(
        "true" if state["readme_changed"] else "false", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact-root", required=True)
    parser.add_argument("--readme-path", default="README.md")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--build-targets-json", required=True)
    parser.add_argument("--force-build", default="false")
    parser.add_argument("--workflow-name", default=".github/workflows/monitor-images.yml")
    args = parser.parse_args()

    readme_path = Path(args.readme_path)
    original_readme = readme_path.read_text(encoding="utf-8") if readme_path.exists() else ""
    old_records = parse_readme_versions(original_readme)
    new_records = load_version_artifacts(Path(args.artifact_root))

    build_targets = load_json_text(args.build_targets_json, {"include": []})
    if not isinstance(build_targets, dict):
        build_targets = {"include": []}

    force_build = args.force_build.lower() == "true"
    changed_apps = semantic_changed_apps(old_records, new_records)
    build_targets_selected = select_build_targets(build_targets, changed_apps, force_build)
    build_matrix = {"include": build_targets_selected}

    rendered_readme = render_readme(original_readme, new_records, args.workflow_name)
    readme_changed = rendered_readme != original_readme
    if readme_changed:
        readme_path.write_text(rendered_readme, encoding="utf-8")

    state = {
        "changed_apps": changed_apps,
        "changed_count": len(build_targets_selected),
        "force_build": force_build,
        "readme_changed": readme_changed,
        "schema_version": 1,
        "versions": new_records,
    }

    report = render_report(state, build_matrix)
    write_outputs(Path(args.output_dir), state, build_matrix, report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
