name: Call Build

on:
  schedule:
    # cloudflare-warp
    - cron: "0 22 * * *"
    # adguardvpn-cli
    - cron: "10 22 * * *"
    - cron: "10 22 * * *"
    - cron: "10 22 * * *"
    # expressvpn
    - cron: "20 22 * * *"
    # nordvpn
    - cron: "20 22 * * *"
    # squid
    - cron: "30 22 * * *"
    # vlmcsd
    - cron: "30 22 * * *"
    # novnc
    - cron: "40 22 * * *"
    # baidunetdisk
    - cron: "40 22 * * *"
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: UTC

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        schedule_time:
          # cloudflare-warp
          - {
              time: "0 22 * * *",
              app_branch: "cloudflare-warp",
              tag_repo: "latest",
              force_push: "false",
            }
          # adguardvpn-cli
          - {
              time: "10 22 * * *",
              app_branch: "adguardvpn-cli",
              tag_repo: "nightly",
              force_push: "false",
              custom_env: "update_channel=nightly",
            }
          - {
              time: "10 22 * * *",
              app_branch: "adguardvpn-cli",
              tag_repo: "beta",
              force_push: "false",
              custom_env: "update_channel=beta",
            }
          - {
              time: "10 22 * * *",
              app_branch: "adguardvpn-cli",
              tag_repo: "release",
              force_push: "false",
              custom_env: "update_channel=release",
            }
          # expressvpn
          - {
              time: "20 22 * * *",
              app_branch: "expressvpn",
              tag_repo: "latest",
              force_push: "false",
            }
          # nordvpn
          - {
              time: "20 22 * * *",
              app_branch: "nordvpn",
              tag_repo: "latest",
              force_push: "false",
            }
          # squid
          - {
              time: "30 22 * * *",
              app_branch: "squid",
              tag_repo: "latest",
              force_push: "false",
            }
          # vlmcsd
          - {
              time: "30 22 * * *",
              app_branch: "vlmcsd",
              tag_repo: "latest",
              force_push: "false",
            }
          # novnc
          - {
              time: "40 22 * * *",
              app_branch: "novnc",
              tag_repo: "latest",
              force_push: "false",
            }
          # baidunetdisk
          - {
              time: "40 22 * * *",
              app_branch: "baidunetdisk",
              tag_repo: "dev",
              force_push: "false",
            }

    steps:
      - name: Trigger build-docker
        if: ${{ github.event_name == 'schedule' && github.event.schedule == matrix.schedule_time.time }}
        env:
          workflow: "build-docker"
        working-directory: /
        run: |
          # Create base JSON using jq
          data=$(jq -n \
            --arg app_branch "${{ matrix.schedule_time.app_branch }}" \
            --arg tag_repo "${{ matrix.schedule_time.tag_repo }}" \
            --arg force_push "${{ matrix.schedule_time.force_push }}" \
            '{ ref: "main", inputs: { app_branch: $app_branch, tag_repo: $tag_repo, force_push: $force_push } }')

          # Check if 'custom_env' is defined and not empty, then add it
          if [[ -n "${{ matrix.schedule_time.custom_env }}" ]]; then
            data=$(echo "$data" | jq --arg custom_env "${{ matrix.schedule_time.custom_env }}" '.inputs.custom_env = $custom_env')
          fi

          # Output the final JSON data for debugging (optional)
          echo "$data" | jq .

          # Use the generated data with curl
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.workflow }}.yml/dispatches \
            --data "$data"
          