name: Fetch (Dev)

run-name: Fetch Matrix for Docker

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  fetch-layers:
    name: Fetch Docker layers (Matrix)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # 同时针对多个镜像、多个平台
        image_name: ["alpine:latest", "debian:latest", "ubuntu:latest"]
        arch_branch: ["linux/amd64", "linux/arm64"]
    steps:
      - name: Setup environment
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install -y ca-certificates curl gpg skopeo jq

      - name: (MetaData) from DockerHub
        id: meta-image
        env:
          category: "repository"
          # 把冒号和斜杠都替换成下划线，以便生成合法的文件名  1. GitHub Actions 的表达式中不支持 Bash 风格的字符串替换 (如 //[:\/]/_)。  2. 可以使用内置函数 replace( <string>, <search>, <replace> ) 递归替换冒号 (:) 和斜杠 (/)。
          file_prefix: ${{ replace(replace(matrix.image_name, ':', '_'), '/', '_') }}
          file_suffix: ${{ replace(replace(matrix.arch_branch, ':', '_'), '/', '_') }}
        run: |
          # 初始化存储元数据的 JSON
          metadata='{"repository":[]}'

          repo="${{ matrix.image_name }}"
          platform="${{ matrix.arch_branch }}"
          echo "Inspecting image: $repo for platform: $platform"

          os=$(echo "$platform" | cut -d'/' -f1)
          arch=$(echo "$platform" | cut -d'/' -f2-)

          variant=""
          if echo "${arch}" | grep -q "arm/v"; then
            variant=$(echo "${arch}" | cut -d'/' -f2)
            arch=$(echo "${arch}" | cut -d'/' -f1)
          fi

          data_json=$(skopeo inspect \
            --override-os="${os}" \
            --override-arch="${arch}" \
            ${variant:+--override-variant="${variant}"} \
            --format=json \
            docker://docker.io/"${repo}" | jq .)

          metadata=$(jq \
            --argjson data "${data_json}" \
            --arg platform "${platform}" \
            --arg repo "${repo}" \
            '.repository += [{name: $repo, platform: $platform, data: $data}]' <<< "${metadata}")

          output_file="layers_summary_${{ env.file_prefix }}_${{ env.file_suffix }}.json"
          echo "${metadata}" | jq . > "${output_file}"
          echo "status=success" | tee -a ${GITHUB_OUTPUT}

      - name: (Check) Layer MetaData
        id: check-layer
        env:
          file_prefix: ${{ replace(replace(matrix.image_name, ':', '_'), '/', '_') }}
          file_suffix: ${{ replace(replace(matrix.arch_branch, ':', '_'), '/', '_') }}
        run: |
          meta_file="layers_summary_${{ env.file_prefix }}_${{ env.file_suffix }}.json"
          if [ ! -f "$meta_file" ]; then
            echo "No metadata file found: $meta_file"
            exit 1
          fi

          echo "Reading metadata from: $meta_file"
          metadata_image=$(cat "$meta_file")

          layers=$(echo "${metadata_image}" | jq -r '.repository[].data.Layers | @sh')
          echo "Layers found:"
          echo "${layers}"

          changed=false
          echo "changed=${changed}" | tee -a ${GITHUB_OUTPUT}
          echo "status=success" | tee -a ${GITHUB_OUTPUT}

      - name: Show summary
        env:
          file_prefix: ${{ replace(replace(matrix.image_name, ':', '_'), '/', '_') }}
          file_suffix: ${{ replace(replace(matrix.arch_branch, ':', '_'), '/', '_') }}
        run: |
          meta_file="layers_summary_${{ env.file_prefix }}_${{ env.file_suffix }}.json"
          echo "Final summary for $meta_file:"
          cat "$meta_file"
