name: Call Build

on:
  schedule:
    - cron: "0 12 * * *"
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: UTC

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          [
            {
              workflow: "build-docker",
              app_branch: "adguardvpn-cli",
              tag_repo: "release",
              force_push: "false",
            },
            {
              workflow: "build-docker",
              app_branch: "adguardvpn-cli",
              tag_repo: "beta",
              force_push: "false",
            },
            {
              workflow: "build-docker",
              app_branch: "adguardvpn-cli",
              tag_repo: "nightly",
              force_push: "false",
            },
          ]
      fail-fast: false
    steps:
      - name: Trigger workflow
        id: trigger
        working-directory: /
        env:
          workflow: ${{ matrix.config.workflow }}
        run: |
          data='{
            "ref": "main",
            "inputs": {
              "app_branch": "${{ matrix.config.app_branch }}",
              "tag_repo": "${{ matrix.config.tag_repo }}",
              "force_push": "${{ matrix.config.force_push }}"
            }
          }'
          curl -XPOST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.workflow }}.yml/dispatches \
          --data "$data"
