name: Call Build (Dev)

on:
  # schedule:
  #   # 每天在 UTC 时间 22:00 运行
  #   - cron: "0 22 * * *"
  repository_dispatch:
  workflow_dispatch:

run-name: Build Matrix for Docker

jobs:
  docker:
    name: ${{ matrix.inputs_params.app_branch }}
    uses: ./.github/workflows/build-docker.yml
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        inputs_params:
          - app_branch: "cloudflare-warp"
            tag_repo: "latest"
          - app_branch: "adguardvpn-cli"
            tag_repo: "nightly"
            custom_env: "build_arg='update_channel=nightly'"
          - app_branch: "adguardvpn-cli"
            tag_repo: "beta"
            custom_env: "build_arg='update_channel=beta'"
          - app_branch: "adguardvpn-cli"
            tag_repo: "release"
            custom_env: "build_arg='update_channel=release'"
          - app_branch: "expressvpn"
            tag_repo: "latest"
          - app_branch: "nordvpn"
            tag_repo: "latest"
          - app_branch: "squid"
            tag_repo: "latest"
          - app_branch: "vlmcsd"
            tag_repo: "latest"
          - app_branch: "novnc"
            tag_repo: "latest"
          - app_branch: "baidunetdisk"
            tag_repo: "dev"
          - app_branch: "steamcmd"
            tag_repo: "dev"
          - app_branch: "runner"
            tag_repo: "dev"
          - app_branch: "runner"
            tag_repo: "slim"
            custom_env: "dockerfile=slim.Dockerfile"
          - app_branch: "runner"
            tag_repo: "actions"
            custom_env: "dockerfile=actions.Dockerfile"
          - app_branch: "runner"
            tag_repo: "actions-slim"
            custom_env: "dockerfile=actions-slim.Dockerfile"
    with:
      app_branch: ${{ matrix.inputs_params.app_branch }}
      tag_repo: ${{ matrix.inputs_params.tag_repo }}
      force_push: ${{ matrix.inputs_params.force_push || 'false' }}
      custom_env: ${{ matrix.inputs_params.custom_env || '' }}
      runner-image: ${{ matrix.inputs_params.runner_image || 'ubuntu-24.04' }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
