name: Download File to Artifact

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: "URL to download"
        type: string
        required: true
        default: "https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe"

run-name: Download File to Artifact

jobs:
  download:
    name: Download File to Artifact
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        shell: bash
    container:
      image: ubuntu:devel
      # 按官方文档允许的字段，尽量给满 GHA 可传递的容器运行权限
      options: >-
        --privileged
        --user=0:0
        --pid=host
        --ipc=host
        --uts=host
        --cgroupns=host
        --cap-add=ALL
        --security-opt apparmor=unconfined
        --security-opt seccomp=unconfined
      volumes:
        - /dev:/dev
        - /sys:/sys:ro
        - /sys/fs/cgroup:/sys/fs/cgroup
        - /run/udev:/run/udev:ro
        - /lib/modules:/lib/modules:ro
    env:
      DEBIAN_FRONTEND: noninteractive
      FORCE_UNSAFE_CONFIGURE: "1"
      # ========= Workspace Environment Variables ==========
      compress: true
      PATH_output: "${{ github.workspace }}/output"
    steps:
      - name: Set File URL
        run: |
          echo "::add-mask::${{ github.event.inputs.file_url }}"
          echo "FILE_URL=${{ github.event.inputs.file_url }}" >> $GITHUB_ENV

      - name: Download File
        id: download-file
        run: |
          mkdir -p ${{ env.PATH_output }}
          FILE_NAME=$(basename $FILE_URL)
          FILE_EXT="${FILE_NAME##*.}"
          if [[ "${FILE_NAME}" == "${FILE_EXT}" ]]; then
            echo "::error::Unable to detect file extension from ${FILE_NAME}"
            exit 1
          fi
          echo "::add-mask::$FILE_NAME"
          echo "Downloading file from $FILE_URL"
          curl -sL $FILE_URL -o "${{ env.PATH_output }}/${FILE_NAME}"
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV
          echo "FILE_EXT=${FILE_EXT}" >> $GITHUB_ENV
          echo "file_name=${FILE_NAME}" >> $GITHUB_OUTPUT
          echo "file_ext=${FILE_EXT}" >> $GITHUB_OUTPUT

      - name: Compress File with Advanced Settings
        id: output-compress
        uses: Grinch27/github-actions/.github/actions/compress-xz@main
        with:
          path_target: ${{ env.PATH_output }}
          input_ext: ${{ steps.download-file.outputs.file_ext }}
          split_size: "1900M"
          split_threshold: "2000000000"
          mem_hold: "2048"
          memlimit: "4GiB"

      - name: Upload to artifacts
        uses: actions/upload-artifact@main
        with:
          name: compressed-file
          path: "${{ env.PATH_output }}/*.${{ steps.output-compress.outputs.target_ext }}*"
          retention-days: 1
